# Generated by Django 2.0.6 on 2019-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jodiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginmodel',
            name='dateAccountCreated',
            field=models.DateField(default='2019-01-01'),
        ),
    ]
