# Generated by Django 2.0.6 on 2019-03-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jodiApp', '0002_auto_20190305_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='gameForeignkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jodiApp.UserLoginModel'),
        ),
    ]
